name: C CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target: [ RELEASE, CLANG, DEBUG ]
        
    env:
      TARGET: ${{ matrix.target }}
      CFLAGS: -I/usr/include/json-c/json-c

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libcurl4-openssl-dev libjson-c-dev
    - name: Run info
      run: make info
    - name: Build
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: telegram-bot-${{ matrix.target }}
        path: bin/telegram-bot
